# Generated by Django 2.0 on 2021-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='medicine',
            field=models.TextField(default='medicine'),
        ),
    ]
