# Generated by Django 2.0 on 2021-04-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_case_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='Quantity',
            new_name='cqty',
        ),
    ]
