# Generated by Django 2.0 on 2021-04-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210424_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='Patient_id',
            new_name='patient_id',
        ),
    ]
