# Generated by Django 2.0 on 2021-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctor_doc_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='total',
            field=models.BigIntegerField(default=50),
        ),
    ]
