# Generated by Django 2.0 on 2021-05-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('generalfees', models.BigIntegerField(default=100)),
                ('total', models.BigIntegerField(default=200)),
            ],
        ),
    ]
