# Generated by Django 2.0 on 2021-05-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.BigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.BigIntegerField(max_length=10)),
                ('Subject', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Product',
            new_name='product_id',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
