# Generated by Django 2.0 on 2021-05-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210508_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Contact',
            field=models.BigIntegerField(),
        ),
    ]
